name: 'Terraform CI/CD'
on: [push]

jobs:
  terraform:
    name: 'Terraform Plan and Apply'  # Fix: Ensure this is indented correctly
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: 'Checkout repository'
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Specify the Terraform version you need

      # Step 3: Print PEM File (Masked)
      - name: 'Print PEM File (Masked)'
        run: |
          echo "$MCDEVOPS_GH_APP_PEM_FILE"
        env:
          MCDEVOPS_GH_APP_PEM_FILE: ${{ secrets.MCDEVOPS_GH_APP_PEM_FILE }}

      # Step 4: Terraform Init
      - name: 'Terraform Init'
        run: terraform init
        working-directory: modules/terrafrom_certificates
        env:
          TF_VAR_github_app_pem: ${{ secrets.MCDEVOPS_GH_APP_PEM_FILE }}
          TF_VAR_root_ca_private_key: ${{ secrets.ROOT_CA_PRIVATE_KEY }}

      # Step 5: Terraform Plan
      - name: 'Terraform Plan'
        run: terraform plan
        working-directory: modules/terrafrom_certificates
        env:
          TF_VAR_github_app_pem: ${{ secrets.MCDEVOPS_GH_APP_PEM_FILE }}
          TF_VAR_root_ca_private_key: ${{ secrets.ROOT_CA_PRIVATE_KEY }}

      # Step 6: Terraform Apply (Optional - can comment this out if you want to review the plan manually)
      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
        working-directory: modules/terrafrom_certificates
        env:
          TF_VAR_github_app_pem: ${{ secrets.MCDEVOPS_GH_APP_PEM_FILE }}
          TF_VAR_root_ca_private_key: ${{ secrets.ROOT_CA_PRIVATE_KEY }}

     
